### ISSUE TITLE
Could not autoload puppet/provider/radius/eos when running rspec tests

### ISSUE THREAD

**Issue by jerearista** [arista-eosplus/puppet-netdev#16]
I'm unable to get the tests to run on my system based on the steps in the README:

mkdir /workspace
cd /workspace
git clone https://github.com/puppetlabs/netdev_stdlib
export GEM_NETDEV_STDLIB_VERSION=file:///workspace/netdev_stdlib
git clone https://github.com/arista-eosplus/rbeapi
export GEM_RBEAPI_VERSION=file:///workspace/rbeapi

git clone https://github.com/puppetlabs/netdev_stdlib_eos
cd netdev_stdlib_eos
bundle install --path .bundle/gems/

bundle exec rspec spec

Coverage report generated for  to /workspace/netdev_stdlib_eos/coverage. 0.0 / 0.0 LOC (100.0%) covered.
/workspace/netdev_stdlib_eos/lib/puppet/provider/radius/eos.rb:4:in `require': Could not autoload puppet/type/radius: Could not autoload puppet/provider/radius/eos: cannot load such file -- puppet_x/eos/provider (Puppet::Error)
	from /workspace/netdev_stdlib_eos/lib/puppet/provider/radius/eos.rb:4:in `<top (required)>'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:62:in `load'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:62:in `load_file'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:77:in `block in loadall'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:75:in `each'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:75:in `loadall'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:213:in `loadall'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/metatype/manager.rb:122:in `newtype'
	from /workspace/netdev_stdlib/lib/puppet/type/radius.rb:3:in `<top (required)>'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:62:in `load'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:62:in `load_file'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/util/autoload.rb:199:in `load'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/puppet-3.7.4/lib/puppet/metatype/manager.rb:163:in `type'
	from /workspace/netdev_stdlib_eos/spec/unit/puppet/provider/radius/eos_spec.rb:34:in `<top (required)>'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `block in load_spec_files'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `each'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load_spec_files'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:97:in `setup'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/bin/rspec:23:in `load'
	from /workspace/netdev_stdlib_eos/.bundle/gems/ruby/bin/rspec:23:in `<main>'

**Comment by jerearista** [comment]
rpm -qi puppet
Name        : puppet
Version     : 3.7.4
Release     : 1.fc20
Architecture: noarch
Install Date: Thu 12 Mar 2015 10:21:57 PM EDT
